services:
  db:
    image: postgres:17
    container_name: database
    environment:
      - POSTGRES_USER=Devs4U
      - POSTGRES_PASSWORD=mate
      - POSTGRES_DB=mateverse
    ports:
      - 55432:5432
    volumes:
      - ./psql_data/:/var/lib/postgresql/data
